// Generated by scripts/generate-providers.mjs; do not edit.
import { fixture as fixture0 } from "../src/providers/basecamp/fixtures.js";
import { fixture as fixture1 } from "../src/providers/breeze/fixtures.js";
import { fixture as fixture2 } from "../src/providers/ccb/fixtures.js";
import { fixture as fixture3 } from "../src/providers/cloudflare/fixtures.js";
import { fixture as fixture4 } from "../src/providers/docs/fixtures.js";
import { fixture as fixture5 } from "../src/providers/drive/fixtures.js";
import { fixture as fixture6 } from "../src/providers/forms/fixtures.js";
import { fixture as fixture7 } from "../src/providers/github/fixtures.js";
import { fixture as fixture8 } from "../src/providers/gmail/fixtures.js";
import { fixture as fixture9 } from "../src/providers/infisical/fixtures.js";
import { fixture as fixture10 } from "../src/providers/linear/fixtures.js";
import { fixture as fixture11 } from "../src/providers/mixpanel/fixtures.js";
import { fixture as fixture12 } from "../src/providers/notion/fixtures.js";
import { fixture as fixture13 } from "../src/providers/overflow/fixtures.js";
import { fixture as fixture14 } from "../src/providers/planning-center/fixtures.js";
import { fixture as fixture15 } from "../src/providers/revenuecat/fixtures.js";
import { fixture as fixture16 } from "../src/providers/sheets/fixtures.js";
import { fixture as fixture17 } from "../src/providers/slides/fixtures.js";
import { fixture as fixture18 } from "../src/providers/stripe/fixtures.js";
import { fixture as fixture19 } from "../src/providers/tithely/fixtures.js";
import { fixture as fixture20 } from "../src/providers/vercel/fixtures.js";

export const providerFixtures = [fixture0, fixture1, fixture2, fixture3, fixture4, fixture5, fixture6, fixture7, fixture8, fixture9, fixture10, fixture11, fixture12, fixture13, fixture14, fixture15, fixture16, fixture17, fixture18, fixture19, fixture20];
